### ISSUE TITLE
Image won't start

### ISSUE THREAD

**Issue by Ryonez** [Wonderfall/docker-mastodon#2]
Does this have everything needed? I have not been able to get this to start

Screwing around, I noticed a log somewhere mentioning it can't connect to redis.

**Comment by Wonderfall** [comment]
Sorry I didn't get in touch in time, hope your issue was solved or that you found another working image for you. This image has gone under substantial changes so I'm closing all the issues related to the legacy image.

> Screwing around, I noticed a log somewhere mentioning it can't connect to redis.

This image doesn't provide a redis server, the docker-compose shows how to provide one!

**Comment by Ryonez** [comment]
It's alright. I didn't have a redis server, and still haven't gotten one sorted so I ended up just leaving it be.
